name: Main action

on: [push]

jobs:
  Check-Format-and-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install package with dev option
        run: |
          python3 -m pip install -e ."[dev]"
      - name: Check code format
        run: |
          python3 -m pycodestyle helloworld examples tests
      - name: Check docs format
        run: |
          python3 -m pydocstyle --convention=google helloworld examples tests
      - name: Run tests
        run: |
          python3 -m pytest tests
